import Vue from 'vue';
import Vuetify, {
    VAlert,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckbox,
    VCol,
    VContainer,
    VDialog,
    VDivider,
    VIcon,
    VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemAvatar,
    VListItemContent,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VRow,
    VSpacer,
    VSubheader,
    VTextField,
    VToolbarTitle,
} from 'vuetify/lib';

Vue.use(Vuetify, {
    components: {
        VContainer,
        VRow,
        VCol,
        VCard,
        VCardTitle,
        VCardText,
        VBtn,
        VAlert,
        VListItem,
        VList,
        VListItemAvatar,
        VListItemTitle,
        VListItemSubtitle,
        VListItemContent,
        VListItemIcon,
        VDivider,
        VIcon,
        VNavigationDrawer,
        VSubheader,
        VListItemAction,
        VAppBar,
        VAppBarNavIcon,
        VToolbarTitle,
        VApp,
        VMain,
        VMenu,
        VTextField,
        VSpacer,
        VAvatar,
        VCheckbox,
        VDialog,
        VCardActions,
        VListGroup,
    },
});

export default new Vuetify({
    theme: {
        dark: true,
    },
    icons: {
        iconfont: 'fa',
    },
});
